### ISSUE TITLE
will run into errors if docx package is not installed

### ISSUE THREAD

**Issue by michaelpacer** [suchow/Dissertate#30]
Slightly edited traceback to account for path privacy…but this is the seeming most relevant traceback info…

There also was an issue with \copyrightpage in the Princeton template (I think), but I haven't localized that error yet.

```
Traceback (most recent call last):
  File "../scripts/dissertate-word.py", line 41, in <module>
    main()
  File "../scripts/dissertate-word.py", line 22, in main
    createTemplate(options.school, options.name)
  File "../scripts/dissertate-word.py", line 26, in createTemplate
    SchoolPackage = importlib.import_module("schools." + school + ".word")
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "../scripts/schools/Princeton/word.py", line 2, in <module>
    from ..Generic.generic import GenericTemplate
  File "../scripts/schools/Generic/generic.py", line 2, in <module>
    from docx import Document
```

**Comment by michaelpacer** [comment]
These issues are dealt with by https://github.com/suchow/Dissertate/pull/31 and then as a part of https://github.com/michaelpacer/Dissertate/blob/py3_compat/scripts/build in https://github.com/suchow/Dissertate/pull/35/files.

**Comment by michaelpacer** [comment]
I think this is dealt with so I'll close it.
